[metadata]
name = pre-commit-project
version = 0.1.0

[options]
python_requaires = >=3.10

[flake8]
max-line-length = 120
max-complexity = 10
ignore = D104,D100

[isort]
line_length = 120

[options.extras_require]
pre-commit-hooks = 
                 pre-commit
                 isort
                 flake8
